services:

  zealand-portfolio:
    image: vlysiumdev/zealand-portfolio:latest
    container_name: zealand-portfolio_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - nginx
    volumes:
      - comment_data:/app/PersistentData
    restart: unless-stopped
    mem_limit: 256m

# use reverse proxy container on cloud server
networks:
  nginx:
    external: true

volumes:
  comment_data:
